[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.124.1"
  HUGO_BASEURL = "https://beautiful-quokka-79b409.netlify.app/"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=3153600"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3153600"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=3153600"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
 